name: spot
description: A lightweight and powerful service locator for Dart and Flutter, supporting singletons, factories, async initialization, and scopes with zero dependencies.
version: 1.0.0
homepage: https://github.com/wesleybliss/spot
repository: https://github.com/wesleybliss/spot
issue_tracker: https://github.com/wesleybliss/spot/issues

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
